apiVersion: v1
kind: Secret
metadata:
  name: repo-quick-stickers
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/jaennil/quick-stickers-tg-bot
  username: jaennil
  password: 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
