apiVersion: v1
kind: Secret
metadata:
  name: bot-config
  namespace: sticker-bot
type: Opaque
stringData:
  config.yaml: |
    telegram:
      token: "8158905082:AAEnRNikWoM2W3RyGtwQqD5AfJgEWHmWLgY"
    database:
      driver: "postgres"
      dsn: "postgres://sticker:sticker@postgres:5432/sticker?sslmode=disable"
    ocr:
      engine: "api"
      server_url: "http://ocr:8765"
