apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: sticker-bot
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths":{"ghcr.io":{"username":"jaennil","password":"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"}}}
