apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: sticker-bot
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'api'
        static_configs:
          - targets: ['bot-api:8080']

      - job_name: 'bot'
        static_configs:
          - targets: ['bot:8080']

      - job_name: 'guide-helper-cache'
        static_configs:
          - targets: ['cache.guide-helper.svc.cluster.local:8080']
        metrics_path: '/metrics'

      - job_name: 'guide-helper-tiles'
        static_configs:
          - targets: ['tiles.guide-helper.svc.cluster.local:8080']
        metrics_path: '/metrics'
