apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bot-config
  namespace: sticker-bot
spec:
  encryptedData:
    config.yaml: AgAGxtFyypUb/UlzkOuOsSxYgtkQz63YinybR0jZzla2DacwQeB8Er6PQ1QuMaf9QzczsmNGyV9wvtwwES9n5yxfn2PbgczMDmNUyCUc3E7yqJ43B/V7IrVV28ba2KPNW0ULePCzmBLn43irhL6Frn4waZEuKV25U6VAtSmcQcW7VMmQMS4lHYHf8LfrgYx1AdKTx7EZSYF5RMxLhEkbkWJTZKHOBTsoLI6zMVjd3QvS+tjYlyI6XVGAd+jqp6ZO2gcRREPAHKp5MALHJwAA3vlryv+CpRT4tvDBTUvjH173jTyY5fEA+3V79+ffOqw7kSPhohY2Xyvv2PDlFWQchZCK7nmeN62zDPxV+vGXaX0nZ30UUUJuaVojVjNSbqj9OMMYaVUsCZ+j8qWb7G6U+DxoLX5jtJzDLgvCAAlekBHWFRXcGDRc7woIMSTeBqE1pvRrk5DD7bN4CZwacT+8a7ARPpXM088pulgw5WHSeHsb5T75tSEUBoI0a2tNAIUqFQssDDbKPu8+5yb+kJ6ClU2l9m0pVMqZKvzLROjmXOGPtoJHhxK5xQZ3CRhE3YMkW8AGu4IuSdw6AyCYg5K5g7FFWnSEFEr+EYvB7I+gj09XpSJZL+WcjpdRz3pr/mA1XG9lLZTEDVvfeeIj1mvgGKzXeZkcmfcoIwTLPFxldPRhpY4TvkXaOmLzvnJW2kr/AkUi3dgX8Al0gTp1qIDVKDJf9ipnqRpkAjhyx/yn+54ev6gQKv6PuE4B2uTePqWKO9K+h/Rwc1IAJZIox0MEFozIlmhKmQK1GCwGpeXNJUsy6ONmBsLtRlTT0tYgXrbSO/Qow+EACiVFoJ0e7vMwceGMoQ1Ens4FDtf/Gk6qG2OCxIUKQQ87uf2IRbaTQoX+jrK7FuhAGVioR9dfnGWYepO7eKT/1GyXPLNxf2kUXccJfr+RDGTS8CKPUwJphLvhPHnFgRFXifdoZgH7eLSpR0fpprpwLCsy0A4vjX05DiWA4PPMZVXhhBnNfcRdRMaCNd1aMxr/8FgOsff92zMint6TBbm2EQv1x9ty1Qi9a29X5xldk6vu5a8JNIEWXlFrpmbegrdkYK52KonCadWT44NJmAEGR4Pxxw/fkoU87/8Y9xVyHYUuAU5Q5z7/rcLAGyU1kmm0Nsl1JtTvO/Euh4qJloIX4w/kfVqdxMTfBWhKXXhTizAf
  template:
    metadata:
      name: bot-config
      namespace: sticker-bot
