---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bot-config
  namespace: sticker-bot
spec:
  encryptedData:
    config.yaml: AgAxKTdHc3asqdRGEfxjfh/DDD2kbn2xiMvzwShYxUHdTELI0wTQzLRsbPx2NcwKANR/2q00USrg/ETji9ltG/OPoCqOnLnMNzm1jvOnp+T5ViGRqilF+5C/H8zAG8kSTEIqdLrzUW4kzDcyVihM9T0fw//cj3Dw8MwG/veoU2RpYMNqgQez1PGRYLKW1df3cJ3yEnKoKFSvc7X9Thylw6kjyi2v2zf5TVLW13P2cRlkm8dtSfp0oPkiR5YW40devlSFgAMN0M+Cu7YTpG0jIeNO/LXOVltA9tf34sSxb0iBpqyNaVPavAxwJs9sf2llJFB/lCka4C8jDaTbrdP/VaId/tRxaIX7vt+M3uQgTvneG8VAlg2/yhxK34xVFl4Qre7jBpAjuuoBmbrSOJXIu5KJNk9VDv/342Dyk8L7KdvBN20BT8Zt7AFmAwYKChpW7vT046Awx8fj1GqFqhH+fbEnJgiwtZb74JmOs6IqZlDn7m+MRl824hqMkZScJc/g89cqLIcfD/agIUwaZ4Eh41QnGwvCrP45Zb9EDI/rv9B1zZRPdvPmgU664YrO36bwX+eyKZ/Cmbng9o2cipswjthaBtnE6TYWV7/3KF58yS37CbxaF+0cApAQ/itf9utPnYgL2niV1a7n9qSI9ZOQPsPI6l/z4x7KlA2zLsfyr8C5IF3HNCCWVSP6Q5BtJh76A4Zks9kFsVp597jw2CySKZxNUfhs/vYH5ZBLAYHZmTzVF4hqc8finEL7BMfnl0prrXaPjwP7XHUndy3VmRpQxmn4XNJxXNTTkSeMtekUU8D+TUsdr0m6rnOMNMgAoXRmDoFtA8lAzL626AcKJeR1TaPnG7Cu7a4ftXhqXvwzDj8Dum1VsMS05TrptsV2SZP9TK8TKFGJC0FcFOwhzu3mWKRYLIsb/eFZMrOMIoaK+jjJb8mMn6aEVguCpRhi0F0GW4ZkQQVfNbw3+FNJ2sojRjDItLvrVMq5pod7JtLeEcpLuCkhMeG2Il13AWOLjTYzyswHIbLaTwCnqg1AxF3zrlWzuSIWa45kcWnRxYHrE+LToGqGW2tTz2yjNFsBDcEZoBLbZSaXAOo86ZRj922PaPuZnfhiDTtXnBwY6u3iZwRFYdmkTY2qm0ITEr+fWEAwg2fhNTO+HgM9ZZn5zfVaNj5L5xkZy33UqsioLw==
  template:
    metadata:
      name: bot-config
      namespace: sticker-bot
    type: Opaque
