---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bot-config
  namespace: sticker-bot
spec:
  encryptedData:
    config.yaml: AgCIPcIEbPQEpTs59R+eRCGDz7qbRQcMwL5kF2BmheD7vQKU0G+Hj7LLdr4Rj5NeO+3rzK38Hvf+eySR7mtZ1to+7sGXryXMmsQc+NPOhe4Mxxa0oTvYY7q4EY7jCIHoVroKYPrjadyFhJLktNUU0FQjvaqQtZVQv7XNy8BlE2LciKRCM9FkMjXPSG4nA0ii9UG4H3zsbPumBrxQZ62MP0VRx6TEqHan3NSkg1ObRTatWDU2fwPZG5QsQQt1iUILUqLW1BycR3VopPmVvB5pFQygnkWREFwe0v9B9tYj286we2QykbFf0FCRK7A5QDpzuxvPYWMVkpVQp+ETJNOrgObM9pqXd6JSRgWbo0QW5E/akwGxoEVrLQin98C9G4wt1g0iirtz4gyudQW7d7518s1cXl7WTq9T9ucj/YqcGD908S3b406HIh1zXAcVOVWQnlgd7uD1GPxoipTHfG3ZxzqPHtXqEJ8w5OX7XkuHEzwG/6gu9Z/PF1w5LV4i0GMosS8jBO6ghwFDiEKnHrb4qi1iMTZpTt4fX+gflRSSq9aMz0srT713YtESQJEXqZRMo9OuWdpfPKMziYVBUnHDgY8XC8JcT8ddOYYI+BpE3uxNHPfAJc1kTixeUWUfLQir35+mQSt6A1LMBYVWTOo0rILQgCDyIy3ZOgiHSdnXrOyf5t+qkybPdhIN12kduWLvS608Z7iUCpZn1di+R+zDm531Uz9PBtYzArmpvigdumGjN9xEqcLydY6maw3/EJww+ss0q3nA/B0mz22/E/w4+uk8DIEAG+9N/nyIU09lcV//W0DqY+kjpSnguLrQrGma+5x87qOafgGWGS3FlAxtoHpWKN1H/Jxz0E/dKoUkZq7YFFMk6l29wkf/eWmws7crzc0cdB6YZeZpN5XL18ZSJT9557ZT2YpKnoveB3qYHbKNAccpio1w4ba+Nduyf2gu8QPs5WbyoLS1DspEZYdtWVxx6Alwchj1Y1TE5sLywqhgOyoLrPkfmYRfAPyvPGB/EFOpV0uKk32Ire0icx5u/zXyUkhmnQSrV91Cq0S8kPDVnX5jMiJqmDqujnZFccsc2D5Kxqi3HozAE+LgFdYRk+6tgTRgH8P+wKG1qiZqtMgvO0j1p4p4xO2h46HAYHu+Yl9HHyu9kAznl3rXrA1lON97HfKOnMOgAW4FAnKQSxKQYbR4x3z5dxLihaYZPPbK4FmeZCKSn5UtyuZ9jnO9Ew8DBZm3e04gDy48wV9i4pPtzch5rgNrx2iGCXF5vOU6p/l4QdzD0vhIPIHwXuklHT4CSMSAaAdrb/lWZT8KdglHxFEHM0/nmpJVJvbVSQVqehu3AEL5VHbCavdOWpj3Utas0b6kiS1cHSrSlYL3ReodYbIF8zp+8Q==
  template:
    metadata:
      name: bot-config
      namespace: sticker-bot
