---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: sticker-bot
spec:
  encryptedData:
    .dockerconfigjson: AgAFeDKN4xRst9TMS2mH7fows4DjAIwLLLqgd+7PiWfBiWZASkLQzQRyrQFOBa4WedumghDmHMY65jCnBOtiZqTX+WGkymOpctaqt1NiU2N6i22SfRXpEd2HY3iqtvcSY10zfL1h5Sd7LUziW5Mlg96VKQ5gbySzj8fhRsgG+FW60OB4NvCzMGrOciWdgrX846Ztuc3U/wPy02wCp9cQyVF58/ZT0fWXqdlfvpE9TrpsxYnnolqXpphuigLAhZhtL0YK1/TMFgWUzqxlCEkwulDRKVdaOF0/4JGgmMh2QGVSoL2h6bcU6GwzeFSuF9eKoakrZYRjkqC1T44xEdTlkuTLp4Hba6FFTs545Y3Jei/PabHHF1C0reh3RmC/Ep6UFou30yfd0HiU+ijVP7aM/vrhKmhJ/5rNtScSung5GHRzoxCR3ai7kqtwRtj0XXjjMKoca2p9CihpLvx7rI7EH3lprcolj4PJCJVFL5x5fMRLNRW9uBl2/ZqjEpGtv5Cscm+lDYt3eJLefAoqpWADkSwuiuO6OBHJEPzloUQDJ1XekeY8HYQgKp3QFRCt9g/r9I/jEe9b/NgKULu/zoa6EJKWST9DLP6bc5EuhjPyXyH5A/r1RWJ99fnnxp7oyOyHTtJE0ORwvYrCfAlZ9+BzWqYJlfOxiUsxtxa6VcfHKPjG9/cXbqMburZrP3gHWlZ/sWaGynLdjXovdmfNRJf/ezv3fLq36/gRz8QLDMAMQ5tbXp9V+70zcpCUygkkSZhTOERORecVHA53PqfNM9KNkJurymcE1bQxycN7+YTt7ol6XQm/et61ZO5DhDsNERGdGzfHYHQHqD4ypLAxTy2/z3rT+JviDreDhRVzzYIth53hOBmqsLvxkJ38hJ3G69DvutNDCAICqKY+hr88ZmYGmsd8gckRiayAwgjSK/W3
  template:
    metadata:
      name: ghcr-secret
      namespace: sticker-bot
    type: kubernetes.io/dockerconfigjson
