---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: sticker-bot
spec:
  encryptedData:
    .dockerconfigjson: AgBU/rPzAH7ah0ZPRrYIGIyMtut+AzNWaAuvd+6mI9bclX384upStf/V+lX9Hw6wyPTboZdfRs+OKPXWcr1MhXyrhZ/9TwBYwy9nJuH8A39S7c9yhIkh6cw9063bvsYWj6AwRgE22XswCoUfKLmKV6m3LAlWJtuffWRxLL6feQYB6LlHtXwXH939ylED1va2ZBAVb+FKSzmIZe4L3gmIsOpq3Yq08sgrhWwlvnyYTvm90R+GQZmABRXKaj/rBG179T/KqafR8Kll4w90HD1TNfp0fnP2JmAJd8sjFcmxOiQMH7gO1VbNllOVvtVgzB8x42fCsAv4fGGzXoI6e3eR+t/ZV5GtYhNR4czGpJTsJpx1dpNqa6KaPM0QprYPeqyxyTU40Vma3MaomWmStnIzaVzTiTeYUv3lnJ9X+GCJNSnGMW6+RydzYyBsg1yRJzM4dYPWfYq5OhqWn+rmCtWbGYW/R6Am5JpIX2sU6h8JbqVaY6Jj5JakDPnk8URVn8IMaKyqhDTD3DCoxMoLCoIa3xTAH4iY1L79LTi9F2SrBCx29f/vTTFak2PDi0H9XR0mM96lhJbjNybeiXnM1DFNqwhWDubtnWLG1y5BwM3yx04EA5xB5wFfdNfd21G2J3RCcDPk2qxawT37XZ/CKqXNeDjywWCI2EK/wDHpOUK3qp6yQK3m1WtElwpydmZ592ZH7D27F2sacE9U73TzYAK36ysj0uyG1szJB6jh8OJw2ciKTUSqozjm9h+vvc7l85idsjXvXK3IO7zqjCJbMBgpgunnrh/1MjOOZkjKZMBpIYd6egq5Y6/idlqWG0HTjIBQYGZGcxsiuaCsnnIK0kH2uAiExduUB+oZHh0Wy5+vZVtVywOataIjHugmrq5sCDX4f0214A2UBI+LUcg/E8zqsWL+1EsC0wU3NKNfcPQd
  template:
    metadata:
      name: ghcr-secret
      namespace: sticker-bot
    type: kubernetes.io/dockerconfigjson
