---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: sticker-bot
spec:
  encryptedData:
    .dockerconfigjson: AgB2+69VAuOwb4NaZiLc3sXSJfgRZx3A38J5Fl7X095XCBjCzWM8maybdqF0WxaIPpVa6TX5Cp8S2KqZdeA9Axa5vjopgxmwGPaEFBUpcvCA6QYdlthlAVdZtg57g54q65ObSk+yN4DSiByRKNCOAt/bKS+poOX9bPoflZLgrY0nh69uayyCtHOV64wnjyhX0WO9wBqeNzyQi2BBAFOpX6gzzSRlveIGcNhQjmsCvu6N4uZHwnRafFuJa7mstLckk23g7pDZHSs9vr6e4LyGuimf4czg+YxNjjw6ABoubuV18zj7S5Bhqk3iA1yZpFlx5/ylmTYpFEQ0RmCE0bxHevQVDxvn4zpOJfHrp6wcbcL8GsLHxpV5A7NTfo+daJpNrQKXIe3+WRtECWJwgdCej6TnViwLRST8ghBkCU1MZKFJRDNQXRfen0CgMogMuSa5cL27pFDWBQ5zeT1DWX7lPPkpd3MF4IAZ5idbcngnVjrIJcW0YxVmapmyAk7zUJJyDtPo2CcnIilE20dRXjwFBaLlBwuFpdsSfdpFp8A0GQL9EDiKmw1qD3YDrYKcAdwSygxdxccHCihsNQYnLpiumuaHtLSKTJAvyA2coLhYXhkaizMuA0HgA63HjeEUjV+2kZ9PysVHdyOJJzaZJjrfKCbhD5gWVlK1QHAYx7iyHUNJo8nNF3ix6jFr0U0CrY3eAl0OmPh6tAJ065CNCGWnoZgLaGjfa/Y4Wk8wAcHa/iyMJ5HDMZIGJ9QcjChtMOddF9/nQhUIkpd3uWil7uaXDsgc6HRaHtvwZrWvCMvkPFg/QJGZDgS6q5DQvoPUu/V7RlHNyPQysWJX6jGP0QrygQAwX/Q/Yq4HOMMzMxoe3a6HThaDTLWfpHHuaxhGaW/4k1trbkY7tWIAPO5AvINfctEoNFFVWVjP/EpWMNNoqC3ryHwFX3NwmoR+iGgzt+SBJgkUCEgvWOgbvvXAsruG6H9WeuFAkrp0WXw=
  template:
    metadata:
      name: ghcr-secret
      namespace: sticker-bot
    type: kubernetes.io/dockerconfigjson
