apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sticker-bot

resources:
- ../../base
- ingress.yaml
- bot-config-sealed.yaml
- ghcr-sealed.yaml
- postgres-sealed.yaml

images:
- name: api
  newName: ghcr.io/jaennil/quick-stickers-tg-bot/bot
  newTag: 3581e83d07740c5e286dad014dc11a9b425e80b2
- name: bot
  newName: ghcr.io/jaennil/quick-stickers-tg-bot/bot
  newTag: 3581e83d07740c5e286dad014dc11a9b425e80b2
- name: xray
  newName: teddysun/xray
  newTag: 1.8.24
