apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sticker-bot

resources:
- ../../base
- ingress.yaml
- bot-config-sealed.yaml
- ghcr-sealed.yaml
- postgres-sealed.yaml

images:
- name: api
  newName: ghcr.io/jaennil/quick-stickers-tg-bot/bot
  newTag: 7bb012b8ea5199a1fd7230f32d28f61778201a64
- name: bot
  newName: ghcr.io/jaennil/quick-stickers-tg-bot/bot
  newTag: 7bb012b8ea5199a1fd7230f32d28f61778201a64
- name: xray
  newName: teddysun/xray
  newTag: 1.8.24
