---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: sticker-bot
spec:
  encryptedData:
    password: AgAlihcMzfvJoEzCLRgVLuFc7MPUpLR7RQr/zy9jqi2ugkxmobsiNQAUuLIGgf15+0l741uc0Zws+yh+ljRNWS8TNbKuqqDTA8pQ2UZCNhmHlWeoeb9nqJHQF6QsZXU2RtNsyApeHi+E1bQH4+j0ewtRjaYW7iOwUzDkUsM6wEeNfBhogJT+7DXqseXK2oT2TZ/YY6strzIL/ub3ZM6EqGyAL5qOHMxoJ9c0hyFlgjb1Sg9MKK0nGH/DsfPlWV0F7BixGFFVXsH7lbuX39uYSB/EbjaWqznsCvlY+s7JWV3+dhMc1WhuWnP+z769p8xbaM4ZrEIlvIqtgzCF4789185NMKWWZXQKMGva3z6pyI8Q8zQ1+B4HA99ZsZ+Psl5EyIfqekRk5LXqlKev+k5l/33u0pQr+zc4oAVXzi5T/mFoHPjQKEmgD/gTv2frxGmi9V//lQZw+oao6XEvvGj2ScpVSWMpO7OQGYZdfTrbQhL8WM6b+LBI2G/ACxfOvVwpgD3jXHUfGYo6i2mLj+oK72FdGXhm2EFzP620zhHwZbTlyUKOtOOea2/QNoIJOR1d6Ko6dDnh/MLOguAlEkMUM9sXI6nQ0daVi5AGq8a5/zdRROqv7cOZLE2+UTwnAGsJafSKVL4kYKkQNMGuDfJAobSiZKyHSTqZVJsFGMI1CJ5GHW4xEcHT92b++4u/pImn0Zl94a6rnBFI
    username: AgAxjIPSVZJ6fOKHjlNAw+YmEKvtMT0dHUBJFqF5oROa+Mv2IlJd9/mprVrJoHWEYCz5UXBhRz3VNUV1iAzyB6FKi0A61WFKzDfy4Q4yxqDlUmiBTnslPq5Kfnfrg78u3srKO8xbnIKruGV1YlBnepq9DkudyR8VjnZUxoUL4qHTt07RNI3UrVbk96JKYxNkpT6CstqIA0MyrVX/9uffUFvwfpg2kyyaeWC6r7tiwPOd1M9HPg9aKGfa12sduwgqEExJsDcV4lXEbYSdb6fnkJGeSchOY4jA4KjLNYmbw1xfv6zOnpeaK4OSluoKQZ/easN+fp7102ST8aytXElcBn7keFLML2VThdZjNjrF/aX2pOPvYKS9CSLc2M0fHE+xeN3xvmce0vCa5vGRLCrFIRDpHKs1eZEY/6MaedUEpEa9x4xL44WxAPHTFxTqYZInvbb7FuMdp/0wr23xFA3bP+MZb5UYGss4JiOeIrBgqSf9FR0MpCFYxn06XdY/7SBnl0/Gk+ICMFwFcmPYOaiUIp0r4QqNSG4t1WSzHyj8+Ttdfg4MPFpW/lv0ORvC6BEjbLq4cwWyOGSaqLXfsal0EoXOcOLTuBfKCQXca1ViWCIHvOPsd2k5m9lOMbKBacIVMbhp4kZ7JSHIOpL0WcGGE8mt1bkx2beva4IDM1C3iPs8NliPnO2WaqZpGPprhcRx6V8EruHgOl7H
  template:
    metadata:
      name: postgres-credentials
      namespace: sticker-bot
    type: kubernetes.io/basic-auth
