---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: sticker-bot
spec:
  encryptedData:
    password: AgCCxW6oOjGgtaXDPxDxt1ZNG6eiEOamDaAheAXIquqRCUeRN56nZncp0Yd6G8lh4Fu6FCRUvGqW90mVX2qoj7oepL6AbPdcdvXVC9DEMpjZk+L5ko4d/XtdX4meVAGmUIZNXIr/FIxxuu1R1b/2Fv3df/4bRU/+UOaZxpJluOTFqYJVk+BhynmZ7jZAoV15OXQdVWytTm9Sm2oYRWo/xMsiE6XMwyILTwmrz4MGFSyj+1hAo2LhmERzE0+9peGcyXobi2txdqZwpz5e04lfzX3iR6UHzGdKa68TbWAIOcUlfTEH5yr0s2dJKskCpsMs/SpZzUsCp1vRLXX+WeKCh2Nn4Q5KiRjFwg93JQZNs9qMAiK+Ynm0+kPj92cVODhejSNpGzdeUH3m1WGlTi7faqlO/l+Xp0/Qp8eIyPnCCxMpmBb41ThVGGVEBvvQ9UkvrXBdS9TTchNrwpyxo6lNdet3v1LJLRGxDQmphvZJsMdd8uSgIoGTdoGZMbuNVp3RUaBmjMBFzEyerMT56+/EwPOPb/P4jCXorq5WVKTr0VVXw2heLK+FGeGxY+RT3TKOga4XDT8VX8/m20Z5GLbSyFnhuwdWFDEKnPuPtSEOGvlU2YoT1KuQNg3MSwv4eFpp1L/ghHNvNEsn7M9dnO2NQcaxttJXbeaqkDjn1sp5zYnbQ/BXzaC016OlxvI648+pyGeN87oZNW4i
    username: AgBSYh7s/CZq3mfP5eD49ykbaAaOIYc7iWlo40boOwd1Oj8Sf1t83SKs+iJtnzQlictRWKgfHQCfMthf6sEjUQvqN2zEzeMJNKNJ/zZfRFz2fKr00zRPKvevsf2VVi46YPoY+vn/8hBMoFfqH+brPjbFSehSFoIFCVh3J2SVHn5/3NRzVO0mob2Spz1A6kc4WGxZybafOffeWBP9MZT/qTVkGgYPINKnmADeGkbQRIaRh4EKOJ2EonihbPqX07+oRJZNO/s8RopU6DxCFEqxvImcqLWfTKsBoxjPDD0jZEDR9fMVGE+jAKCq2e/3RfsmeCIy5zqYE36oIkFjNOJ4QNHRdtBoFbODhc5kkHHKPVYh9/Ui7ZckH8QgfcCyTu4pdV/5G9Vyezk77clkxJCFftwPjB4MF25MBVwgZsygiNM1N9bcbF6c9Sf+6LNWq/Qc5ypH0905/h/StgUnZRpOTqfVds8YkS0rLiasV2svzwLVmGlTCdmwaZC3EZXL9Ms7qhCUrdA4mIeTaKO78fLlY6y41tRH/1SDQqMdtIZWi58Xkct/PYwFIA6FcDrwIGoXJ5t1TmuIy2WkgjeVilABdyIsrvJOtHUgl+Ochr+I+vSRKa4VGMa+cBjNMyKXjEGFErhoPVrDmbxPgShqX3LfeP7wmZ20jbd1Pdc596fyGxVLerqIQQv1n5f6K+SNUAt98H1L7LCtZQFC
  template:
    metadata:
      name: postgres-credentials
      namespace: sticker-bot
    type: kubernetes.io/basic-auth
