---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: sticker-bot
spec:
  encryptedData:
    password: AgDB2q291vZSVF9AAtupci9Izkh8INCplIDImF5C4u7ntWmtpi1SJJPnHknnSbgC00yuOCVfgvP8fK/u0bv4aBr7qXMEt3NJqK4HwymmWMYhB+j6jM5+j9GDPUl38FWQkFZ8hr1Bct51InFOsW/UlIiXbAomlsaVAMJ2I+YSMomHClOSLt/ouEErdA6Hv84WV2xPKD113zlWJuLPeLIZIHy4f/9LyauYidMu/pymauB7JZQ1XhwXiSOQJll4BeIfonMxugdjnz5WV9Y+Eo21idAABKuoP5b01WJaaL7pW2/1fjJGIjPaF1/E+Ua1tWluqH/Tw1GIHIsKRjUcXNB0+EdyaCSw75NvmxSI1tVKxjXo5sj/up0c3bT3KDvqZQsj8sOh0nNOCQtmCoHbIzDE4tOyTIN1raJkYykDfq81LLNxVCBDj7h5Ys25DPtFzDfDpKLVrg+kRehJL2RByTgyAPxaheanKoo4Teii5gEJRLDF9Z27YeiiCyFGEFIJh3iun2iZuPdZdy9pQroqnuZ3Ogh4YXs6Cxxtb/BFB8u4FwAWMQeeUSLEntiIOAZDvopVL3gYS2SSLkSjXTvYdYdj8u6IXw/ylzX7xBVetRF/HV80TTnmwPiD3dkCGKJdM7YSQrQiTvv/VZiSTpcQXcUZLMsRfwNHTvScRb2dmabBufiGuEqXnGXUrZM7F5TpqJZuuxyqBQCRX3Cp
    username: AgDqD/10yYqWi5yhXwPLe+FifKc6uwwNFmnBKGaRd4hDXYGL39uP40jS6K1Ukgm5ydsaKnIgw/LzUqdSnqsnPMXSTGPeC2rfTI/fv1b5YYZ9FCbLAQX1pJ5hG6upZ7o7OTqESSq7pf4qsdE15MB7EuRDRT9v+iugIj14I8H5oNrhUGL98h9wjvBx7t+IFDZ/tpNGC5DKUceXjC3vr1zbRYkQoE2Gu1aj5iaRcNfrX0FK43s7vp5M85kx/Cli41P7yKpK31EwCMlXF/2rlaAxgUzhJFun0H10EJMlQmptVqP4gL+xTgeDdnxP02qTnFNtGt4KkK+ucQPXDDt1tlvW9nhedRATZtloFfWQ2aVP9ysgVo4ph2yMk2cqhCkaQ2mE1zrBEIEtJBnfuFF6v/uCqP/mWQEqQxVBqRWcnI4Dg12sj0rTavuaf3XTa25cZ94Dezv/HCQMrypjWKKO1PJlpDhCvU1yo7cxQSSHkR5v62VJQH8cqBsH9MHvdocRrxHzqyMvvWs8Jr1MjjAxttzKAk++E560rk8ec+XERemToj8CHaok9QCPZD/dp4NWs/paR8gMGaqBEhbofDi0VUlZe8Bif7jiOeFg0NRj40PtRaw4FZRzXLpitXjTJZfbV+OG82dJNisXQOjg+ep882s18j8n3t/GN8+0laTUzQcwYScqlnWQL/dWTcDJCM4Rv319Ifsqw07bI6j9
  template:
    metadata:
      name: postgres-credentials
      namespace: sticker-bot
    type: kubernetes.io/basic-auth
