telegram:
  token: "8158905082:AAEnRNikWoM2W3RyGtwQqD5AfJgEWHmWLgY"

database:
  driver: "postgres"
  dsn: "postgres://sticker:sticker@postgres-cluster-rw:5432/sticker?sslmode=disable"

ocr:
  engine: "api"
  server_url: "http://ocr:8765"  # local OCR server URL (use Docker service name in Docker)
  proxy_url: "socks5://host.docker.internal:2080"  # optional: SOCKS5 or HTTP proxy for ocr.space (use host.docker.internal in Docker)
  space_api_keys:
  - "K81763554688957"
  - "K84899834788957"
  - "K83802716488957"
