telegram:
  token: "8158905082:AAEnRNikWoM2W3RyGtwQqD5AfJgEWHmWLgY"

database:
  driver: "postgres"
  dsn: "postgres://sticker:sticker@postgres-cluster-rw:5432/sticker?sslmode=disable"

ocr:
  proxy_url: "socks5://xray.proxy.svc.cluster.local:1080"  # shared SOCKS5 proxy from homelab-infra
  space_api_keys:
  - "K81763554688957"
  - "K84899834788957"
  - "K83802716488957"
