telegram:
  token: "8158905082:AAEnRNikWoM2W3RyGtwQqD5AfJgEWHmWLgY"

database:
  driver: "postgres"
  dsn: "postgres://sticker:sticker@postgres:5432/sticker?sslmode=disable"

ocr:
  proxy_url: "socks5://xray.proxy.svc.cluster.local:1080"  # in Kubernetes use shared xray service; for Docker use host.docker.internal:2080
  space_api_keys:
  - "K81763554688957"
  - "K84899834788957"
  - "K83802716488957"
