apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sticker-bot

resources:
  - namespace.yaml
  - bot/deployment.yaml
  - bot/service.yaml
  - api/deployment.yaml
  - api/service.yaml
  - postgres/cluster.yaml
  - servicemonitor.yaml
  - dashboard.yaml
