apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bot
  labels:
    app: bot
spec:
  selector:
    matchLabels:
      app: bot
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
