apiVersion: v1
kind: ConfigMap
metadata:
  name: xray-config
data:
  config.json: |
    {
      "log": {
        "loglevel": "warning"
      },
      "inbounds": [
        {
          "tag": "socks-in",
          "port": 1080,
          "listen": "127.0.0.1",
          "protocol": "socks",
          "settings": {
            "udp": true
          }
        }
      ],
      "outbounds": [
        {
          "tag": "proxy",
          "protocol": "vless",
          "settings": {
            "vnext": [
              {
                "address": "de1.gofizzin.com",
                "port": 443,
                "users": [
                  {
                    "id": "e529239b-0b1b-4b81-968c-fad29edd5f91",
                    "encryption": "none",
                    "flow": "xtls-rprx-vision"
                  }
                ]
              }
            ]
          },
          "streamSettings": {
            "network": "tcp",
            "security": "reality",
            "realitySettings": {
              "serverName": "de1.gofizzin.com",
              "fingerprint": "chrome",
              "publicKey": "zl_ufoBxXwRSPvxTIJEqFIIaewNT_1fYtxI9rWXRtwg",
              "shortId": "ba15d0ae"
            }
          }
        },
        {
          "tag": "nl1",
          "protocol": "vless",
          "settings": {
            "vnext": [
              {
                "address": "nl1.gofizzin.com",
                "port": 443,
                "users": [
                  {
                    "id": "e529239b-0b1b-4b81-968c-fad29edd5f91",
                    "encryption": "none",
                    "flow": "xtls-rprx-vision"
                  }
                ]
              }
            ]
          },
          "streamSettings": {
            "network": "tcp",
            "security": "reality",
            "realitySettings": {
              "serverName": "nl1.gofizzin.com",
              "fingerprint": "chrome",
              "publicKey": "yvYNgYXNwbIBZ0PRhe_kE24DBdvQHT4uEkKJwzjxIiI",
              "shortId": "4a1f9d0a"
            }
          }
        },
        {
          "tag": "se1",
          "protocol": "vless",
          "settings": {
            "vnext": [
              {
                "address": "se1.gofizzin.com",
                "port": 443,
                "users": [
                  {
                    "id": "e529239b-0b1b-4b81-968c-fad29edd5f91",
                    "encryption": "none",
                    "flow": "xtls-rprx-vision"
                  }
                ]
              }
            ]
          },
          "streamSettings": {
            "network": "tcp",
            "security": "reality",
            "realitySettings": {
              "serverName": "se1.gofizzin.com",
              "fingerprint": "chrome",
              "publicKey": "dIcaKW8h24YgsrTYmzzevZFe8QxkQAHNtfQ7g9N1vko",
              "shortId": "67106660"
            }
          }
        },
        {
          "tag": "fi1",
          "protocol": "vless",
          "settings": {
            "vnext": [
              {
                "address": "fi1.gofizzin.com",
                "port": 443,
                "users": [
                  {
                    "id": "e529239b-0b1b-4b81-968c-fad29edd5f91",
                    "encryption": "none",
                    "flow": "xtls-rprx-vision"
                  }
                ]
              }
            ]
          },
          "streamSettings": {
            "network": "tcp",
            "security": "reality",
            "realitySettings": {
              "serverName": "fi1.gofizzin.com",
              "fingerprint": "chrome",
              "publicKey": "u6TamAtY_Dx-Bexb5euDt4Tbm9bldhD8qWAaHECXhio",
              "shortId": "f8785f1e"
            }
          }
        },
        {
          "tag": "lv1",
          "protocol": "vless",
          "settings": {
            "vnext": [
              {
                "address": "lv1.gofizzin.com",
                "port": 443,
                "users": [
                  {
                    "id": "e529239b-0b1b-4b81-968c-fad29edd5f91",
                    "encryption": "none",
                    "flow": "xtls-rprx-vision"
                  }
                ]
              }
            ]
          },
          "streamSettings": {
            "network": "tcp",
            "security": "reality",
            "realitySettings": {
              "serverName": "lv1.gofizzin.com",
              "fingerprint": "chrome",
              "publicKey": "Py2HuGdujeX0pnn0s3MOJ55jN29odLVtvT8LdMxQGxw",
              "shortId": "10de098a"
            }
          }
        },
        {
          "tag": "pl1",
          "protocol": "vless",
          "settings": {
            "vnext": [
              {
                "address": "pl1.gofizz.in",
                "port": 443,
                "users": [
                  {
                    "id": "e529239b-0b1b-4b81-968c-fad29edd5f91",
                    "encryption": "none",
                    "flow": "xtls-rprx-vision"
                  }
                ]
              }
            ]
          },
          "streamSettings": {
            "network": "tcp",
            "security": "reality",
            "realitySettings": {
              "serverName": "pl1.gofizz.in",
              "fingerprint": "chrome",
              "publicKey": "jh6G6JAWc1IoJ-ZfIgqeUKKARzJnTTk4qti21iprkTM",
              "shortId": "d39b0c5e"
            }
          }
        },
        {
          "tag": "ee1",
          "protocol": "vless",
          "settings": {
            "vnext": [
              {
                "address": "ee1.gofizzin.com",
                "port": 443,
                "users": [
                  {
                    "id": "e529239b-0b1b-4b81-968c-fad29edd5f91",
                    "encryption": "none",
                    "flow": "xtls-rprx-vision"
                  }
                ]
              }
            ]
          },
          "streamSettings": {
            "network": "tcp",
            "security": "reality",
            "realitySettings": {
              "serverName": "ee1.gofizzin.com",
              "fingerprint": "chrome",
              "publicKey": "z46-GwLD2TvzK2o95okMP7IMNPUfwYHmqt2JV6nJ03I",
              "shortId": "8c9f899dba63f6c7"
            }
          }
        },
        {
          "tag": "uk1",
          "protocol": "vless",
          "settings": {
            "vnext": [
              {
                "address": "uk1.gofizz.in",
                "port": 443,
                "users": [
                  {
                    "id": "e529239b-0b1b-4b81-968c-fad29edd5f91",
                    "encryption": "none",
                    "flow": "xtls-rprx-vision"
                  }
                ]
              }
            ]
          },
          "streamSettings": {
            "network": "tcp",
            "security": "reality",
            "realitySettings": {
              "serverName": "uk1.gofizz.in",
              "fingerprint": "chrome",
              "publicKey": "UHbwATrfIcPdOXTOUL5pUldKOtzYE2lFmBnr_--AnBo",
              "shortId": "499396ad"
            }
          }
        },
        {
          "tag": "fr1",
          "protocol": "vless",
          "settings": {
            "vnext": [
              {
                "address": "fr1.gofizzin.com",
                "port": 443,
                "users": [
                  {
                    "id": "e529239b-0b1b-4b81-968c-fad29edd5f91",
                    "encryption": "none",
                    "flow": "xtls-rprx-vision"
                  }
                ]
              }
            ]
          },
          "streamSettings": {
            "network": "tcp",
            "security": "reality",
            "realitySettings": {
              "serverName": "fr1.gofizzin.com",
              "fingerprint": "chrome",
              "publicKey": "uvYdcBw9FFSxYXpZy5Pr5gzgXan7PWkWJKg940ogxSU",
              "shortId": "50ea8dd3"
            }
          }
        },
        {
          "tag": "us1",
          "protocol": "vless",
          "settings": {
            "vnext": [
              {
                "address": "us1.gofizz.in",
                "port": 443,
                "users": [
                  {
                    "id": "e529239b-0b1b-4b81-968c-fad29edd5f91",
                    "encryption": "none",
                    "flow": "xtls-rprx-vision"
                  }
                ]
              }
            ]
          },
          "streamSettings": {
            "network": "tcp",
            "security": "reality",
            "realitySettings": {
              "serverName": "us1.gofizz.in",
              "fingerprint": "chrome",
              "publicKey": "l7CG7y_pIDO7DL4myJzcIWeM_CoXZQfB2RKANKvRuww",
              "shortId": "0e2ed9c9"
            }
          }
        },
        {
          "tag": "direct",
          "protocol": "freedom"
        }
      ],
      "routing": {
        "domainStrategy": "AsIs",
        "balancers": [
          {
            "tag": "proxy-balancer",
            "selector": ["proxy", "nl1", "se1", "fi1", "lv1", "pl1", "ee1", "uk1", "fr1", "us1"],
            "strategy": {
              "type": "random"
            }
          }
        ],
        "rules": [
          {
            "type": "field",
            "network": "tcp,udp",
            "balancerTag": "proxy-balancer"
          }
        ]
      }
    }
